Vagrant.configure("2") do |config|
  config.vm.define "hub-01" do |vm|
    vm.vm.box = "generic/ubuntu2204"
    vm.vm.hostname = "hub-01"

    vm.vm.network "public_network", bridge: "External Virtual Switch"

    vm.vm.provider "hyperv" do |h|
      h.vmname = "hub-01"
      h.cpus = 2
      h.memory = 2048
      h.maxmemory = 8192
      h.auto_start_action = "Nothing"
      h.auto_stop_action = "ShutDown"
      h.linked_clone = false
      h.enable_virtualization_extensions = false
      h.enable_checkpoints = true
      h.enable_automatic_checkpoints = false
      h.enable_enhanced_session_mode = false
      h.ip_address_timeout = 300
      h.vm_integration_services = {
        guest_service_interface: true,
        heartbeat:               true,
        key_value_pair_exchange: true,
        shutdown:                true,
        time_synchronization:    true,
        vss:                     true
      }
      h.mac = "00155DAB0001"
    end

    vm.vm.provision "initial-setup",
      type: "shell",
      path: "scripts/provision.sh",
      privileged: false,
      run: "once"

    vm.vm.provision "install-docker",
      type: "shell",
      path: "scripts/install-docker.sh",
      privileged: false,
      run: "once"

    vm.vm.provision "free-dns-port",
      type: "shell",
      path: "scripts/prepare-systemd-resolved.sh",
      privileged: true, # Since we are touching systemctl and /etc/
      run: "once"

    vm.vm.provision "setup-repository",
      type: "shell",
      path: "scripts/setup-repo.sh",
      privileged: false, # Run as 'vagrant' user, not root
      run: "once",
      env: { "SERVER_IP" => "192.168.1.138", "DOMAIN" => "hub.local" }

    vm.vm.provision "setup-apps",
      type: "shell",
      path: "scripts/setup-apps.sh",
      privileged: false,
      run: "always"

    vm.vm.provision "verify-wildcard-dns",
      type: "shell",
      path: "scripts/check-wildcard-dns.sh",
      privileged: false,
      run: "always",
      env: { "SERVER_IP" => "192.168.1.138" }

    vm.vm.provision "get-system-info",
      type: "shell",
      path: "scripts/vm-info.sh",
      privileged: false,
      run: "always"
  end
end
