Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  # Set the machine name
  config.vm.hostname = "my-ubuntu-box"

  # Simple provision script
  config.vm.provision "shell", inline: "echo hello, $(hostname)"
end